FROM gcr.io/spinnaker-marketplace/gradle_cache
MAINTAINER delivery-engineering@netflix.com
ENV GRADLE_USER_HOME /gradle_cache/.gradle
COPY . workdir
WORKDIR workdir
RUN ./gradlew gate-web:installDist -x test