FROM openjdk:8-jre-alpine
MAINTAINER delivery-engineering@netflix.com
COPY --from=compile /compiled_sources/gate-web/build/install/gate /opt/gate
RUN apk --no-cache add --update bash
RUN adduser -D -S spinnaker
USER spinnaker
CMD ["/opt/gate/bin/gate"]
