FROM ubuntu:bionic
MAINTAINER delivery-engineering@netflix.com
COPY --from=artifact /workdir/gate-web/build/install/gate /opt/gate
RUN apt-get update && apt-get -y install openjdk-8-jre
RUN adduser --disabled-login --system spinnaker
USER spinnaker
CMD ["/opt/gate/bin/gate"]
