FROM alpine:3.11
MAINTAINER delivery-engineering@netflix.com
COPY --from=compile /compiled_sources/gate-web/build/install/gate /opt/gate
RUN apk --no-cache add --update bash openjdk11-jre
RUN adduser -D -S spinnaker
RUN mkdir plugins && chown -R 100:100 plugins
USER spinnaker
CMD ["/opt/gate/bin/gate"]
